### PR TITLE
Adapt plugin to GitBook 3

### PR DESCRIPTION
**Pull request by jpreynat**
Hello,

We will soon release [GitBook v3](https://github.com/GitbookIO/gitbook).
The plugins API has been updated, as you will see [in the GitBook 3 documentation](http://toolchain.gitbook.com/).

I'm in charge of reviewing the existing plugins for maintaining the compatibility with this new version.
In this version, the plugins files will be places under `gitbook/` instead of `gitbook/plugins/`.

The proposed PR has been tested using GitBook 3.
Let me know if you have any remarks regarding what is done, and don't forget to publish a new version if you merge it, specifying the new engine in your package.json:

``` JSON
"engines": {
    "gitbook": ">=3.0.0-pre.0"
}
```

Kind regards,
Johan

### CODE REVIEW

**Comment by clouless** [comment]
Hi Johan,

Very nice :) thx a lot. What a nice service of yours 👍 
I will tend to it this evening.

thx,
Bernhard

**Comment by jpreynat** [comment]
You're welcome. Thanks for your work on extending GitBook's features :)

**Comment by clouless** [comment]
ok I have published v0.1.8
https://www.npmjs.com/package/gitbook-plugin-advanced-emoji

thx :)

**Comment by jpreynat** [comment]
👍  your reactivity!

**Comment by jpreynat** [comment]
Hi @gruenebe,

It seems that you made a first release of the plugin before upgrading the gitbook engine in the `package.json`. This has broken the plugin for GitBook 2 users (since GitBook loads the latest release corresponding to its version).
Could you maybe make two new releases, with something like this:

#### Release `0.1.9`

Plugin folder (in `index.js`):

``` JavaScript
img_dir: "/gitbook/plugins/gitbook-plugin-advanced-emoji/emojis/",
```

GitBook engine (in `package.json`):

``` JSON
"engines": {
    "gitbook": ">=2.5.0"
}
```

#### Release `0.2.0`

Plugin folder (in `index.js`):

``` JavaScript
img_dir: "/gitbook/gitbook-plugin-advanced-emoji/emojis/",
```

GitBook engine (in `package.json`):

``` JSON
"engines": {
    "gitbook": ">=3.0.0-pre.0"
}
```

That would be awesome.
Thanks in advance!

Kind regards,
Johan

**Comment by clouless** [comment]
ok will do, but wasn't the img_dir for v3+ supposed to be without leading and trailing slashes?
`img_dir: "gitbook/gitbook-plugin-advanced-emoji/emojis",`

**Comment by jpreynat** [comment]
My bad, you're correct :)

These are the ones to use:

GitBook 2:
`img_dir: "/gitbook/plugins/gitbook-plugin-advanced-emoji/emojis/",`

GitBook 3:
`img_dir: "gitbook/gitbook-plugin-advanced-emoji/emojis",`

Kind regards,
Johan

**Comment by clouless** [comment]
ok I have it released that way. Should be on npmjs any minute.
- `master` branch is for GitBook v3.x and latest published plugin version is `0.2.0`
- `gitbook_v2` branch is for GitBook v2.x and latest published plugin version is `0.1.9`

**Comment by jpreynat** [comment]
Awesome, thanks 👍

**Pull request merged**
